mutation CreatePlatformKeySignRequest(
  $keyId: String!
  $bitcoinPaymentRequestId: String
) {
  createPlatformKeySignRequest(
    keyId: $keyId
    bitcoinPaymentRequestId: $bitcoinPaymentRequestId
  ) {
   ...PlatformKeySignRequestShared
  }
}
