export const single = [
  "What is your mother's maiden name?",
  "What is your favorite color?",
  "What is your favorite food?",
  "What is the name of your first pet?",
  "What is the name of your high school?",
  "What is your favorite movie?",
  "What is your favorite book?",
  "What is your favorite band/artist?",
  "What is your favorite sports team?",
  "What is your favorite hobby?",
  "What is your favorite vacation destination?",
  "What is the name of your best friend from childhood?",
  "What is the name of your first employer?",
  "What is your favorite TV show?",
  "What is your favorite song?",
];

export const couple = [
  "What is the name of the place where you first met as a couple?",
  "What is the name of the first restaurant you went to together as a couple?",
  "What is the name of the first pet you owned as a couple?",
  "What is the name of the first vacation you took as a couple?",
  "What is the name of the first concert you attended as a couple?",
  "What is the name of the first movie you watched together as a couple?",
  "What is the name of the first book you read together as a couple?",
  "What is the name of the first TV show you watched together as a couple?",
  "What is the name of the first sport you played together as a couple?",
  "What is the name of the first hobby you picked up together as a couple?",
  "What is the name of the first city you visited as a couple?",
  "What is the name of the first place you lived together as a couple?",
  "What is the name of the first employer you both worked for as a couple?",
  "What is the name of the first friend you introduced to each other as a couple?",
  "What is the name of the song that reminds you of your relationship?",
  "What is the name of the place where you had your first romantic kiss?",
  "What is the name of the dish you cook together most often?",
  "What is the name of the movie you've watched together most often?",
  "What is the name of the place you go to for date night?",
  "What is the name of the book you've read together?",
  "What is the name of the place you went to on your honeymoon?",
  "What is the name of the place you go to for anniversaries?",
  "What is the name of the place you go to relax together?",
  "What is the name of the place you go to for long weekend getaways?",
  "What is the name of the place you go to for special events?",
  "What is the name of the place you go to for spontaneous adventures?",
  "What is the name of the place you go to for holidays?",
  "What is the name of the place you go to for celebrations?",
  "What is the name of the place you go to for quiet time together?",
];
