name: Build and Publish Tracker

on: workflow_dispatch

env:
  REGISTRY: ${{ vars.DO_DOCKER_REGISTRY }}
  IMAGE_NAME: tracker
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DO_DOCKER_TOKEN }}
          password: ${{ secrets.DO_DOCKER_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          target: tracker
          push: true
